#!/bin/sh
#
# Starts an x86 qemu VM that boots ...
#

cd "$(dirname $0)" ; dir="$(pwd)" ; cd ../..

VM_QEMU="qemu-system-x86_64" \
  VM_ISO=iso/dfly-x86_64-6.2.2_REL.iso \
  VM_ISO_URL=https://ftp.halifax.rwth-aachen.de/dragonflybsd/iso-images/dfly-x86_64-6.2.2_REL.iso \
  VM_HDA="$dir/disk1.qcow2" \
  VM_HDA_URL="qemu-img-create:-f qcow2 8G" \
  VM_SSH_PORT="$VM_SSH_PORT" \
  VM_FDA="/dev/null" \
  exec bin/vm-launcher
