#!/bin/sh
#
# Starts a qemu VM that boots the standard Alpine Linux image over the internet.
#
# A 4GB harddisk is provided by default, which you can convert to a snoboot image
# using snoboot-prepare-server
#

cd "$(dirname $0)" ; dir="$(pwd)" ; cd ../..

if [ -z "$VM_ISO" ]; then
  VM_ISO=(iso/alpine-standard-3.12.0-aarch64.iso)
  if [ ! -e "$VM_ISO" ]; then
    wget -O "$VM_ISO" "http://dl-cdn.alpinelinux.org/alpine/v3.12/releases/aarch64/alpine-standard-3.12.0-aarch64.iso"
  fi
fi

if [ -z "$VM_BIOS" ]; then
  VM_BIOS=iso/QEMU_EFI.fd
  if [ ! -e "$VM_BIOS" ]; then
    wget -O "$VM_BIOS" "https://releases.linaro.org/components/kernel/uefi-linaro/latest/release/qemu64/QEMU_EFI.fd"
  fi
fi

if [ -z "$VM_HDA" ]; then
  disk1="$dir/disk1.qcow2"

  [ -e "$disk1" ] || qemu-img create -f qcow2 "$disk1" 4G
  VM_HDA="$disk1"
fi

VM_QEMU="qemu-system-aarch64" \
  VM_ISO="$VM_ISO" VM_HDA="$VM_HDA" VM_BIOS="$VM_BIOS" \
  exec bin/vm-launcher
