#!/bin/sh
#
# Starts an x86_64 qemu VM that boots the default snoboot image over the network
#

cd "$(dirname $0)" ; dir="$(pwd)" ; cd ../..

VM_QEMU="qemu-system-x86_64" \
  VM_ISO=iso/ipxe.iso \
  VM_ISO_URL=https://github.com/snoboot/snoboot-ipxe-build/releases/download/test/ipxe.iso \
  VM_SSH_PORT="$VM_SSH_PORT" \
  exec bin/vm-launcher
