#!/bin/sh
#
# Starts an x86_64 qemu VM that boots the default snoboot image over the network
#

cd "$(dirname $0)" ; dir="$(pwd)" ; cd ../..

VM_QEMU="qemu-system-x86_64" \
  VM_ISO=iso/ipxe-x86_64.iso \
  VM_ISO_URL= \
  VM_SSH_PORT="$VM_SSH_PORT" \
  exec bin/vm-launcher
